config/routes.rb
Rails.application.routes.draw do
  
  resources :preferences do 
    member do
      post "select"
    end
  end
  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  resources :games do
    member do
      get "join"
      get "leave"
      get "get_info" 
    end
  end

  devise_for :users
  
  

  root 'home#home'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Easymatch</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
    <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

</head>

<body>
    <div id="modal-holder"></div>
    <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>
    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <%= link_to "Easymatch", root_path %>
                </li>
                <li>
                    <%= link_to "Games", games_path %>
                </li>
                <li>
                    <%= link_to "New Game", new_game_path %>
                </li>
                <li>
                    <%= link_to "Preferences", preferences_path %>
                </li>
                <% if !user_signed_in? %>
                <li>
                    <%= link_to "Sign in", new_user_session_path %>
                </li>
                <li>
                    <%= link_to "Sign up", new_user_registration_path %>
                </li>
                <% end %>
                <% if user_signed_in? %>
                <li class="log">
                    Logged in as 
                    <div class="log-mail">
                        <%= current_user.username %>
                    </div>
                    <% if user_signed_in? %>
                    <div>
                        <%= link_to "Log out", destroy_user_session_path, method: :delete %>
                    </div>
                    <% end %>
                </li>

                <% end %>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-8">
                        <%= yield %>
                    </div>
                    <div class="col-md-4">
                    
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->
    </div>
    <!-- /#wrapper -->

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

</body>

</html>